# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    #### go expects specific checkout path representing url
    working_directory: /go/src/github.com/blupig/echo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      # - run: go get -v -t -d ./...
      - run: go test -v -cover
