# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    # Project path in GOPATH
    working_directory: /go/src/github.com/blupig/echo
    steps:
      # Checkout code
      - checkout

      - run:
          name: "Install packages"
          command: "go get -v -t -d . && go get github.com/mattn/goveralls"

      - run:
          name: "Run tests"
          command: "go test -v -covermode=count -coverprofile=coverage.out"

      - run:
          name: "Report coverage info"
          command: "goveralls -coverprofile=coverage.out -service=circle-ci  -repotoken $COVERALLS_TOKEN"
